# Generated by Django 4.2.7 on 2023-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0002_cart_rendezvous_cartitem_cart_cart_items_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='date_disponible',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
