# Generated by Django 4.2.7 on 2023-12-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0004_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procuratio_app.client')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procuratio_app.transaction')),
            ],
        ),
    ]
