# Generated by Django 4.2.7 on 2023-12-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0005_historiquea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='services_list',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='MP',
            field=models.CharField(choices=[('carte-bancaire', 'carte-bancaire'), ('especes', 'especes')], max_length=150),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='produits_list',
        ),
        migrations.AddField(
            model_name='transaction',
            name='produits_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
