# Generated by Django 4.2.7 on 2023-12-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0006_remove_transaction_services_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='MP',
            field=models.CharField(choices=[('carte-bancaire', 'Carte bancaire'), ('especes', 'Espèces')], max_length=150),
        ),
    ]
