# Generated by Django 4.2.7 on 2023-12-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0007_alter_transaction_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_fidelite',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
