# Generated by Django 4.2.7 on 2023-12-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0008_client_code_fidelite'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fidelity',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_fidelite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
