# Generated by Django 4.2.7 on 2023-12-09 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('procuratio_app', '0009_client_fidelity_alter_client_code_fidelite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sessions.session')),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_sessions',
            },
        ),
    ]
