# Generated by Django 4.2.7 on 2023-12-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0010_clientsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsession',
            name='session',
        ),
        migrations.AddField(
            model_name='clientsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False),
        ),
    ]
