# Generated by Django 4.2.7 on 2023-12-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0011_remove_clientsession_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='reservation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
