# Generated by Django 4.2.7 on 2023-12-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0013_client_fidelitycount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_fidelite',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
