# Generated by Django 4.2.7 on 2023-12-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procuratio_app', '0015_alter_client_fidelitycount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fidelity',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
